# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basededonnee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfant',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basededonnee.Parent'),
        ),
    ]
