# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basededonnee', '0002_auto_20160114_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='photo',
            field=models.ImageField(default='/home/zacchello/travail/s8/pfa/covoiturage/media/default', upload_to='photos/'),
        ),
    ]
